services:
  mail:
    image: bytemark/smtp
    restart: always

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env

  clickhouse:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - postgres
      - clickhouse
      - mail
    ports:
      - 8001:8001
    env_file:
      - ./envs/plausible.env

  redis:
    image: redis:7.0.9
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  server:
    image: adjsky/evil-cards_server:latest
    restart: always
    deploy:
      replicas: 2
    env_file:
      - ./envs/server.env

  load-balancer:
    image: adjsky/evil-cards_load-balancer:latest
    restart: always
    env_file:
      - ./envs/load-balancer.env
    ports:
      - 1337:1337
    depends_on:
      - redis
      - server

  client:
    image: adjsky/evil-cards_client:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - plausible

  nginx:
    image: nginx:1.23
    volumes:
      - /etc/ssl:/etc/ssl:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - plausible
      - client
      - server
      - load-balancer

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
