name: evil-cards-dev

services:
  keydb:
    extends:
      file: common.yml
      service: keydb
    restart: "no"
  server:
    image: tilt/server
    depends_on:
      - keydb
    ports:
      - 8000:8000
    environment:
      - KEYDB_URL=redis://keydb:6379
      - CORS_ORIGIN=*
