name: Manual server build/deploy

on: [workflow_dispatch]

jobs:
  server-build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/evil-cards_server:latest
          file: deploy/Dockerfile.server
          platforms: linux/amd64

      - name: Reflect changes on remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs:
            REPOSITORY: ${{ github.repository }}
            APP_PATH: /app
          script: |
            git clone https://github.com/$REPOSTORY.git $APP_PATH/source
            $APP_PATH/source/deploy/update-server.sh
