name: Build and push service

on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service?'
        required: true
        type: choice
        options:
          - server
          - client
          - load-balancer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push ${{ inputs.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client with secrets
        uses: docker/build-push-action@v3
        if: inputs.service == 'client'
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/evil-cards_client:latest
          file: deploy/Dockerfile.client
          platforms: linux/amd64
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"

      - name: Default ${{ inputs.service }} build and push 
        uses: docker/build-push-action@v3
        if: inputs.service != 'client'
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/evil-cards_${{ inputs.service }}:latest
          file: deploy/Dockerfile.${{ inputs.service }}
          platforms: linux/amd64
