name: Manual build, push and deploy

on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service?'
        required: true
        type: choice
        options:
          - server
          - client
          - load-balancer

jobs:
  build-and-push:
    name: Run build-and-push.yml
    uses: ./.github/workflows/build-and-push.yml
    with:
      service: ${{ inputs.service }}
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ inputs.service }}
    needs: build-and-push

    steps:
      - name: Reflect changes on remote server
        uses: appleboy/ssh-action@v0.1.7
        env:
            REPOSITORY: ${{ github.repository }}
            APP_PATH: /app
            SOURCE_DIR: source-${{ inputs.service }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: REPOSITORY,APP_PATH,SOURCE_DIR
          script: |
            git clone https://github.com/$REPOSITORY $APP_PATH/$SOURCE_DIR
            $APP_PATH/$SOURCE_DIR/deploy/scripts/update-${{ inputs.service }}.sh
