name: Deploy services

on: 
  workflow_dispatch:
    inputs:
      client:
        description: client
        type: boolean
      server:
        description: server
        type: boolean
      load-balancer:
        description: load-balancer
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.service.name }}
    if: matrix.service.run
    
    strategy:
      matrix:
        service:
          - name: client
            run: ${{ inputs.client }}
          - name: server
            run: ${{ inputs.server }}
          - name: load-balancer
            run: ${{ inputs.load-balancer }}
    
    steps:
      - run: echo ${{ matrix.service.name }}

#     steps:
#       - name: Deploy ${{ inputs.service }}
#         uses: appleboy/ssh-action@v0.1.7
#         env:
#             REPOSITORY: ${{ github.repository }}
#             APP_PATH: /app
#             SOURCE_DIR: source-${{ inputs.service }}
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           envs: REPOSITORY,APP_PATH,SOURCE_DIR
#           script: |
#             git clone https://github.com/$REPOSITORY $APP_PATH/$SOURCE_DIR
#             $APP_PATH/$SOURCE_DIR/deploy/scripts/update-${{ inputs.service }}.sh

  purge-cache:
    needs: deploy
    if: inputs.client

    name: Purge cloudflare cache
    runs-on: ubuntu-latest
    
    steps:
      - run: echo hI!

#     steps:
#       - name: Purge cloudflare cache
#         uses: nathanvaughn/actions-cloudflare-purge@v3.1.0
#         with:
#           cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
#           cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
