name: Build and push service

on:
  workflow_dispatch:
    inputs:
      client:
        description: client
        type: boolean
      server:
        description: server
        type: boolean
      load-balancer:
        description: load-balancer
        type: boolean
      deploy-env:
        description: Environment
        type: choice
        options:
          - prod
          - stage

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    name: Generate service matrix

    outputs:
      matrix: ${{ steps.generate-service-matrix.outputs.matrix }}

    steps:
      - name: Generate service matrix
        id: generate-service-matrix
        run: |
          MATRIX_ARRAY=$(node -e 'console.log(JSON.parse(process.argv[1])' '${{ toJSON(inputs) }}')
          echo ::set-output name=matrix::${MATRIX_ARRAY}

  build-and-push:
    if: false
    runs-on: ubuntu-latest
    name: Build and push ${{ matrix.service }}
    needs:
      - generate-matrix

    strategy:
      matrix:
        service: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USERNAME }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}-${{ inputs.deploy-env }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: deploy/dockerfiles/Dockerfile.${{ matrix.service }}
          platforms: linux/amd64
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          target: runner-${{ inputs.deploy-env }}
