name: Build and push service

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service?"
        required: true
        type: choice
        options:
          - server
          - client
          - load-balancer
      deploy-env:
        description: Environment
        type: choice
        options:
          - prod
          - stage

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push ${{ inputs.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USERNAME }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/client-${{ inputs.deploy-env }}

      - name: Build and push client with sentry auth
        uses: docker/build-push-action@v3
        if: inputs.service == 'client'
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: deploy/dockerfiles/Dockerfile.client
          platforms: linux/amd64
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          target: runner-${{ inputs.deploy-env }}

      - name: Build and push ${{ inputs.service }}
        uses: docker/build-push-action@v3
        if: inputs.service != 'client'
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: deploy/dockerfiles/Dockerfile.${{ inputs.service }}
          platforms: linux/amd64
          target: runner-${{ inputs.deploy-env }}
