name: Build and push service

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service?"
        required: true
        type: choice
        options:
          - server
          - client
          - load-balancer
      deploy-env:
        description: Environment
        type: choice
        options:
          - prod
          - stage

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push ${{ inputs.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client with secrets
        uses: docker/build-push-action@v3
        if: inputs.service == 'client'
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/evil-cards_client_${{ inputs.deploy-env }}:latest
          file: deploy/dockerfiles/Dockerfile.client
          platforms: linux/amd64
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          target: runner-${{ inputs.deploy-env }}

      - name: Default ${{ inputs.service }} build and push
        uses: docker/build-push-action@v3
        if: inputs.service != 'client'
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/evil-cards_${{ inputs.service }}_${{ inputs.deploy-env }}:latest
          file: deploy/dockerfiles/Dockerfile.${{ inputs.service }}
          platforms: linux/amd64
          target: runner-${{ inputs.deploy-env }}
