name: Update master NGINX

on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    name: Build and push NGINX

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USERNAME }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Copy NGINX config
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: deploy/nginx/master/conf.d/default.conf
          target: /etc/nginx/conf.d/default.conf
          debug: true
          rm: true

      - name: Update config
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            service nginx reload
