name: Manual client build/deploy

on: [workflow_dispatch]

jobs:
  client-build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/evil-cards_client:latest
          file: deploy/Dockerfile.client
          platforms: linux/amd64
