name: Manual services deploy

on: 
  workflow_dispatch:
    inputs:
      client:
        description: 'Deploy client?'
        type: boolean
      server:
        description: 'Deploy server?'
        type: boolean
      load-balancer:
        description: 'Deploy load-balancer?'
        type: boolean

jobs:
  deploy:
    strategy:
      matrix:
        service:
          - name: "client"
            run: inputs.client
          - name: "server"
            run: inputs.server 
          - name: "load-balancer"
            run: inputs.load-balancer
        
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.service.name }}

    steps:
      - name: Reflect changes on remote server
        if: matrix.service.run
        uses: appleboy/ssh-action@v0.1.7
        env:
            REPOSITORY: ${{ github.repository }}
            APP_PATH: /app
            SOURCE_DIR: source-${{ matrix.service }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: REPOSITORY,APP_PATH,SOURCE_DIR
          script: echo ${{ matrix.service.name }}
#           script: |
#             git clone https://github.com/$REPOSITORY $APP_PATH/$SOURCE_DIR
#             $APP_PATH/$SOURCE_DIR/deploy/scripts/update-${{ matrix.service }}.sh

  purge-cache:
    if: inputs.client
    name: Purge cloudflare cache
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - run: echo HI!

#     steps:
#       - name: Purge cloudflare cache
#         uses: nathanvaughn/actions-cloudflare-purge@v3.1.0
#         with:
#           cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
#           cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
