name: Start services

on: [workflow_dispatch]

jobs:
  start-services:
    runs-on: ubuntu-latest
    name: Start services

    steps:
      - name: Start services
        uses: appleboy/ssh-action@v0.1.7
        env:
          REPOSITORY: ${{ github.repository }}
          APP_PATH: /app
          SOURCE_DIR: source-services-start
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: REPOSITORY,APP_PATH,SOURCE_DIR
          script: |
            git clone https://github.com/$REPOSITORY.git $APP_PATH/$SOURCE_DIR
            $APP_PATH/$SOURCE_DIR/deploy/scripts/start-services.sh
